target "CareGiverApp" do
  use_frameworks!

  #pod 'amplify-tools'

  #pod 'Amplify'
  #pod 'AWSPluginsCore'
  #pod 'AmplifyPlugins/AWSAPIPlugin'
  
  pod 'AWSCore'
  pod 'AWSMobileClient'
  pod 'AWSUserPoolsSignIn'
  pod 'AWSAuthUI'
  
  pod "EstimoteProximitySDK"
end
