# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CareGiver' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CareGiver
  pod 'AWSMobileClient', '~> 2.12.1'      # Required dependency
  pod 'AWSAuthUI', '~> 2.12.1'            # Optional dependency required to use drop-in UI
  pod 'AWSUserPoolsSignIn', '~> 2.12.1'   # Optional dependency required to use drop-in UI
  pod 'AWSAppSync', '~> 2.15.0'           # For AppSync GraphQL API
  pod 'EstimoteProximitySDK'              # For Estimote Proximity SDK
end
