# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CareGiver' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CareGiver
  pod 'AWSAppSync', '~> 3.0.2'

end
